import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import axios from "axios";

export default function Home() {
  const [city, setCity] = useState();
  // @ts-ignore
  const onSubmit = async (e) => {
    e.preventDefault();
    const res = await axios.get("/api/city/getCity");
    const data = await res.data;

    console.log("====================================");
    console.log(data);
    console.log("====================================");
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* @ts-ignore */}
        <form onSubmit={onSubmit}>
          <input
            type="text"
            onChange={(e) => {
              // @ts-ignore
              setCity(e.target.value);
            }}
          />
          <button type="submit">Get City</button>
        </form>
      </main>
    </>
  );
}
